# Generated by Django 4.2.7 on 2023-11-28 09:57

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0035_e40_legal_body_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='e1_crm_entity',
            name='vector_search_speedup_set',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
